server:
  port: 6001

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://47.98.189.37:20280/eureka/
spring:
  cloud:
    gateway:
## 这里可以通过java config的方式配置mapping, @see RouteMappingConfiguration
#      routes:
#        - id: service1
#          uri: lb://service1
#          predicates:
#            - Path=/api-a/**
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
#     如果你的项目中包含了spring-cloud-starter-gateway，但你不想启动网关的时候
      enabled: true
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: TRACE